# Generated by Django 3.1.7 on 2021-02-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='id_key',
            new_name='car_id',
        ),
    ]
